apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sb-kv
  namespace: globoticket
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "__KV_PROVIDER_CLIENT_ID__"
    keyvaultName: "__KEY_VAULT_NAME__"
    tenantId: "__TENANT_ID__"
    objects: |
      array:
        - |
          objectName: service-bus-connection-string
          objectType: secret
        - |
          objectName: eventcatalog-db-conn
          objectType: secret
        - |
          objectName: shoppingbasket-db-conn
          objectType: secret
        - |
          objectName: ordering-db-conn
          objectType: secret
        - |
          objectName: discount-db-conn
          objectType: secret
        - |
          objectName: marketing-db-conn
          objectType: secret
  secretObjects:
    - secretName: sb-secrets
      type: Opaque
      data:
        - objectName: service-bus-connection-string
          key: ServiceBusConnectionString
        - objectName: eventcatalog-db-conn
          key: EventCatalogConnectionString
        - objectName: shoppingbasket-db-conn
          key: ShoppingBasketConnectionString
        - objectName: ordering-db-conn
          key: OrderingConnectionString
        - objectName: discount-db-conn
          key: DiscountConnectionString
        - objectName: marketing-db-conn
          key: MarketingConnectionString